language: node_js
node_js:
- '10'
- '8'
- '6'
- '5'
- '4'
install:
- npm install
script: npm run coverage
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  skip_cleanup: true
  on:
    branch: master
  email: PostalCodesJS@cimpress.com
  api_key:
    secure: pjukBZZa2TjCOqXLSTXzOTVSakalh22PyCHnRNk5MNwcys05aG5C4oB9PIFJfGMPBqqcMt7iE99xGY3zbJ32A9MucG5QOn8a1rbokmNvKTGCvVGsQfZAgmCvm+eZhrLVxqNiapXzN++ezmLTJ+2/ycYUTigToRYIY42aG6eY4MOqWLRPMg0RBDSUqYh5aG4DVXbz3dI9wiqOAAnUVC3S7TqKSvr7BHatgnQmeZUMW843lwhfbTCtPpzUtN24Enp78Nwzlt70rdI6niFVg3XBAT6NlPbg8Js2HYfxBTAgwCEJQRCYRBcufMfC7U4tl7azZa9rJUXQD5nlpY5eYrsrSslZXGHpl2WpVxop9Tze4t51/xUfmCx4t59d2ng5i+JmQhQ2/NUpYAAqvr4yHrAxprNKa4rxzMkM4O9Wn3e7H6LqPrmLmznuUBx0rRE/vrKd6BmVMh0YDa6fS/52n0HUdv2lD7DwGRo922xR3xFJn4UbweK2pmyAD9XROO+IPQyWF/dZOfFKK9PNq6+86E16JzjCasH5wJbqjJnu1D91SeKx9zgfCSI2q3Exx7IAURhAN58wCqbJf3xC27ee4EP4WDwR8FC/OYD5Ag914odpj2SqjjsXxKWEBA+gtMfzl8wLjCgQr+JITCDHOSitNBUpGesT+a13zYF5ljWvUxQSsH0=
